CTEST1:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth #the pipeline was breaking with service-account at the dbt job.
      project: "de-1st-project" # <--- HARDCODED
      dataset: "CTEST1"         # <--- HARDCODED
      location: "EU"
      threads: 4
    

